variables:
  DOCKERFILE_LOCATION: docker/ubuntu.Dockerfile
  IMAGE: ${CI_REGISTRY_IMAGE}/ubuntu
  TAG: ${CI_COMMIT_REF_SLUG}
  CONAN_USERNAME: micro-libraries
  CONAN_CHANNEL: default
  CONAN_EXTRA_OPTIONS_DEV: ""
  CONAN_EXTRA_OPTIONS: ""

default:
  tags: [saas-linux-small-amd64]
  image: ${IMAGE}:${TAG}
  interruptible: true
  timeout: 10m

.code-block-conan-build-init:
- git remote set-url origin https://gitlab-ci-token:${CI_JOB_TOKEN}@${CI_SERVER_HOST}/${CI_PROJECT_PATH}.git
- conan config install conan/config
- NAME=$(conan inspect ${CONANFILE} --format json | jq -r '.name')
- VERSION=$(conan inspect ${CONANFILE} --format json | jq -r '.version')
- conan remove "${NAME}/${VERSION}@${CONAN_USERNAME}/${CONAN_CHANNEL}" -c || true

build-image:
  image: docker:latest
  services:
    - docker:dind
  variables:
    DOCKER_TLS_CERTDIR: /certs
  script:
  - echo -n ${CI_JOB_TOKEN} | docker login -u gitlab-ci-token --password-stdin ${CI_REGISTRY}
  - docker build
      --cache-from ${IMAGE}:${TAG}
      --cache-from ${IMAGE}:${CI_DEFAULT_BRANCH}
      --build-arg BUILDKIT_INLINE_CACHE=1
      -f ${DOCKERFILE_LOCATION} . -t ${IMAGE}:${TAG}
  - docker push ${IMAGE}:${TAG}

conan:check-base:
  needs: [build-image]
  variables:
    CONANFILE: conan/base-cmake-library/conanfile.py
  script:
  - !reference [.code-block-conan-build-init]
  - conan create ${CONANFILE} -b missing --user=${CONAN_USERNAME} --channel=${CONAN_CHANNEL}

conan:check-dev:
  needs: [build-image]
  variables:
    CONANFILE: conan/conanfile-dev.py
  script:
  - conan export conan/base-cmake-library/conanfile.py --user=${CONAN_USERNAME} --channel=${CONAN_CHANNEL}
  - !reference [.code-block-conan-build-init]
  - conan create ${CONANFILE} -b missing --user=${CONAN_USERNAME} --channel=${CONAN_CHANNEL} ${CONAN_EXTRA_OPTIONS_DEV}

conan:check:
  needs: [build-image]
  variables:
    CONANFILE: conan/conanfile.py
  script:
  - conan export conan/base-cmake-library/conanfile.py --user=${CONAN_USERNAME} --channel=${CONAN_CHANNEL}
  - !reference [.code-block-conan-build-init]
  - conan create ${CONANFILE} -b missing --user=${CONAN_USERNAME} --channel=${CONAN_CHANNEL} ${CONAN_EXTRA_OPTIONS}

conan:deploy-base:
  needs: [conan:check-base]
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  variables:
    CONANFILE: conan/base-cmake-library/conanfile.py
  script:
    - !reference [.code-block-conan-build-init]
    - conan create ${CONANFILE} -b missing --user=${CONAN_USERNAME} --channel=${CONAN_CHANNEL}
    - conan remote login gitlab ci_user -p ${CI_JOB_TOKEN}
    - conan upload "${NAME}/${VERSION}@${CONAN_USERNAME}/${CONAN_CHANNEL}" -r gitlab
