if(EMSCRIPTEN)
    if(INSTRUCTION_SET STREQUAL "SSE")
        set(SIMD_FLAGS "-msimd128 -msse4.1")
    elseif(INSTRUCTION_SET STREQUAL "NONE")
        set(SIMD_FLAGS "")
    else()
        message(FATAL_ERROR "ERROR only 128-bit SIMD supported on emscripten")
    endif()
else()
    if(INSTRUCTION_SET STREQUAL "NEON" AND CMAKE_SYSTEM_PROCESSOR MATCHES "armv7")
        set(SIMD_FLAGS "-mfpu=neon")
    elseif(INSTRUCTION_SET STREQUAL "SSE")
        set(SIMD_FLAGS "-msse4.1")
    elseif(INSTRUCTION_SET STREQUAL "AVX")
        set(SIMD_FLAGS "-mavx")
    elseif(INSTRUCTION_SET STREQUAL "AVX-512")
        set(SIMD_FLAGS "-mavx512f")
    endif()
endif()
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} ${SIMD_FLAGS}")
